spring.application.name=estoque-api

# Configuracao do Banco de Dados H2 em Memoria
spring.datasource.url=jdbc:h2:mem:estoquedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o Console Web do H2 para ver as tabelas no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cria e atualiza a estrutura das tabelas automaticamente com base nas Entidades
spring.jpa.hibernate.ddl-auto=update

# Mostra as queries SQL executadas no console do Eclipse para aprendizado
spring.jpa.show-sql=true

server.port=8081